/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wiredtiger.db;

public class WT_MODIFY_LIST {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WT_MODIFY_LIST(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WT_MODIFY_LIST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wiredtigerJNI.delete_WT_MODIFY_LIST(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WT_MODIFY_LIST(int count) {
    this(wiredtigerJNI.new_WT_MODIFY_LIST(count), true);
  }

  public void set(int i, Modify m) {
    wiredtigerJNI.WT_MODIFY_LIST_set(swigCPtr, this, i, Modify.getCPtr(m), m);
  }

}
